# Generated by Django 3.0.4 on 2020-04-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgers_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hamburgesa',
            new_name='Hamburguesa',
        ),
    ]
    
    atomic = False
