# Generated by Django 3.0.4 on 2020-04-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgers_api', '0002_auto_20200420_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='imagen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='burgers_api.Ingredientes'),
        ),
    ]
