# Generated by Django 3.0.4 on 2020-05-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgers_api', '0003_auto_20200422_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='imagen',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
